
BOOKS = [
    {
        'bookTitle': "Z.P.G.", 'imgUrl': 'foobar','author':"Aleen Matei",'id':1},
    {'bookTitle':"For Neda",'imgUrl': 'foobar','author':"Sayer Simms",'id':2},
    {'bookTitle':"Shock and Awe: The Story of Electricity",'imgUrl': 'foobar','author':"Dulci Hobson",'id':3},
    {'bookTitle':"Virunga",'imgUrl': 'foobar','author':"Benetta Lodwig",'id':4},
    {'bookTitle':"Ferngully: The Last Rainforest",'imgUrl': 'foobar','author':"Wenda Lotwich",'id':5},
    {'bookTitle':"Valiant",'imgUrl': 'foobar','author':"Perri Ebourne",'id':6},
    {'bookTitle':"King of Devil's Island (Kongen av Bastøy) ",'imgUrl': 'foobar','author':"Luce Farnall",'id':7},
    {'bookTitle':"Comedy of Innocence (Comédie de l'innocence)",'imgUrl': 'foobar','author':"Mariana Rollins",'id':8},
    {'bookTitle':"His Girl 'Fiday'",'imgUrl': 'foobar','author':"Wait Jeandin",'id':9},
    {'bookTitle':"Babes in Arms",'imgUrl': 'foobar','author':"Ray Fillimore",'id':10},
    {'bookTitle':"Twice-Told Tales",'imgUrl': 'foobar','author':"Josie Halsey",'id':11},
    {'bookTitle':"Clearing, The",'imgUrl': 'foobar','author':"Gregorius Leads",'id':12},
    {'bookTitle':"Hell Without Limits (Lugar sin límites, El)",'imgUrl': 'foobar','author':"Lurette Summerley",'id':13},
    {'bookTitle':"Taxi for Tobruk",'imgUrl': 'foobar','author':"Kinny Romanski",'id':14},
    {'bookTitle':"Once Upon a Time (Der var engang)",'imgUrl': 'foobar','author':"Margalo Pods",'id':15},
    {'bookTitle':"I Heart Huckabees",'imgUrl': 'foobar','author':"Olag Perche",'id':16},
    {'bookTitle':"This Property is Condemned",'imgUrl': 'foobar','author':"Asa Maleby",'id':17},
    {'bookTitle':"Blair Witch Project, The",'imgUrl': 'foobar','author':"Ellie Garling",'id':18},
    {'bookTitle':"Voyager (Homo Faber)",'imgUrl': 'foobar','author':"Addia Patmore",'id':19},
    {'bookTitle':"Tenebre",'imgUrl': 'foobar','author':"Ambrose Barden",'id':20},
    {'bookTitle':"C.H.O.M.P.S.",'imgUrl': 'foobar','author':"Eward Keher",'id':21},
    {'bookTitle':"Halo Legends",'imgUrl': 'foobar','author':"Marina Bolitho",'id':22},
    {'bookTitle':"Sixteen Candles",'imgUrl': 'foobar','author':"Linnea Colgrave",'id':23},
    {'bookTitle':"Rocky Horror Picture Show, The",'imgUrl': 'foobar','author':"Randal Kliemchen",'id':24},
    {'bookTitle':"101 Dalmatians (One Hundred and One Dalmatians)",'imgUrl': 'foobar','author':"Dianne Addekin",'id':25},
    {'bookTitle':"Notorious",'imgUrl': 'foobar','author':"Hilda Heenan",'id':26},
    {'bookTitle':"Adonis Factor, The",'imgUrl': 'foobar','author':"Eden Leckenby",'id':27},
    {'bookTitle':"Joy 'ide'",'imgUrl': 'foobar','author':"Madelene Blabey",'id':28},
    {'bookTitle':"Wrestling Queens",'imgUrl': 'foobar','author':"Freeman Robert",'id':29},
    {'bookTitle':"Patton Oswalt: Werewolves and Lollipops",'imgUrl': 'foobar','author':"Tina Sawfoot",'id':30},
    {'bookTitle':"Tiny Furniture",'imgUrl': 'foobar','author':"Leland Oxenford",'id':31},
    {'bookTitle':"Forgotten, The",'imgUrl': 'foobar','author':"Corri Chaudrelle",'id':32},
    {'bookTitle':"Xala",'imgUrl': 'foobar','author':"Waiter Totterdell",'id':33},
    {'bookTitle':"Tainted",'imgUrl': 'foobar','author':"Claresta Buddleigh",'id':34},
    {'bookTitle':"Val Lewton:  The Man in the Shadows",'imgUrl': 'foobar','author':"Minna 'Bidgman'",'id':35},
    {'bookTitle':"Long Good 'Fiday' The",'imgUrl': 'foobar','author':"Mick Vallery",'id':36},
    {'bookTitle':"Ender's Game",'imgUrl': 'foobar','author':"Estele Semple",'id':37},
    {'bookTitle':"Atlantic City",'imgUrl': 'foobar','author':"Olympe Thoday",'id':38},
    {'bookTitle':"Shadow, The",'imgUrl': 'foobar','author':"Tulley Lante",'id':39},
    {'bookTitle':"Scooby-Doo! WrestleMania Mystery",'imgUrl': 'foobar','author':"Grayce Leavry",'id':40},
    {'bookTitle':"Suzy",'imgUrl': 'foobar','author':"Vannie Lux",'id':41},
    {'bookTitle':"Desperate Search",'imgUrl': 'foobar','author':"Mariska Woolhouse",'id':42},
    {'bookTitle':"Love Me Tonight",'imgUrl': 'foobar','author':"Berni Roote",'id':43},
    {'bookTitle':"Fearless Vampire Killers, The",'imgUrl': 'foobar','author':"Sly Pottberry",'id':44},
    {'bookTitle':"Last King of Scotland, The",'imgUrl': 'foobar','author':"Anabelle Arthurs",'id':45},
    {'bookTitle':"Dennis the Menace",'imgUrl': 'foobar','author':"Jacintha Swayte",'id':46},
    {'bookTitle':"Miss Pettigrew Lives for a Day",'imgUrl': 'foobar','author':"Lani Langlois",'id':47},
    {'bookTitle':"Down Terrace",'imgUrl': 'foobar','author':"Tasia Melross",'id':48},
    {'bookTitle':"Misérables, Les",'imgUrl': 'foobar','author':"Kellen Baseley",'id':49},
    {'bookTitle':"Sorrow and the Pity, The (Le chagrin et la pitié)",'imgUrl': 'foobar','author':"Kameko Charleston",'id':50},
    {'bookTitle':"Mater and the Ghostlight",'imgUrl': 'foobar','author':"Broderic Sebastian",'id':51},
    {'bookTitle':"Coelacanth: The Fish That Time Forgot",'imgUrl': 'foobar','author':"Trescha Ruse",'id':52},
    {'bookTitle':"Yellow Submarine",'imgUrl': 'foobar','author':"Doe Authers",'id':53},
    {'bookTitle':"Earth Dies Screaming, The",'imgUrl': 'foobar','author':"Cori Spaice",'id':54},
    {'bookTitle':"Day After Trinity, The",'imgUrl': 'foobar','author':"Philbert Guswell",'id':55},
    {'bookTitle':"Patriots, The (Patriotes, Les)",'imgUrl': 'foobar','author':"Geneva O'Regan",'id':56},
    {'bookTitle':"Blubberella",'imgUrl': 'foobar','author':"Reggie Hrycek",'id':57},
    {'bookTitle':"Scenes of a Sexual Nature",'imgUrl': 'foobar','author':"Alasdair Snartt",'id':58},
    {'bookTitle':"Grand Canyon",'imgUrl': 'foobar','author':"Cesar Shadwick",'id':59},
    {'bookTitle':"Flight of the Navigator",'imgUrl': 'foobar','author':"Granger Cowherd",'id':60},
    {'bookTitle':"O'Horten",'imgUrl': 'foobar','author':"Cinderella Glencorse",'id':61},
    {'bookTitle':"El Lobo",'imgUrl': 'foobar','author':"Tabitha Parkyn",'id':62},
    {'bookTitle':"Snake in the Eagle's Shadow (Se ying diu sau)",'imgUrl': 'foobar','author':"Rosabella Zanre",'id':63},
    {'bookTitle':"Great Train Robbery, The",'imgUrl': 'foobar','author':"Town Terrelly",'id':64},
    {'bookTitle':"Boys Diving, Honolulu",'imgUrl': 'foobar','author':"Dionis Bleby",'id':65},
    {'bookTitle':"Glass Web, The",'imgUrl': 'foobar','author':"Peta Scrafton",'id':66},
    {'bookTitle':"The Town that Dreaded Sundown",'imgUrl': 'foobar','author':"Sim McMichael",'id':67},
    {'bookTitle':"Perfect 'Canidate' A",'imgUrl': 'foobar','author':"Miran Humphris",'id':68},
    {'bookTitle':"Slender Thread, The",'imgUrl': 'foobar','author':"Antonietta Edsell",'id':69},
    {'bookTitle':"Secret in Their Eyes, The (El secreto de sus ojos)",'imgUrl': 'foobar','author':"Land Stihl",'id':70},
    {'bookTitle':"Screwed",'imgUrl': 'foobar','author':"Kelcy Meadway",'id':71},
    {'bookTitle':"The Well",'imgUrl': 'foobar','author':"Onofredo Olenichev",'id':72},
    {'bookTitle':"The Amazing 'SiderMan' 2",'imgUrl': 'foobar','author':"Garald Fontel",'id':73},
    {'bookTitle':"Jack and Jill",'imgUrl': 'foobar','author':"Maude Denkel",'id':74},
    {'bookTitle':"Full Body Massage",'imgUrl': 'foobar','author':"Ertha Sahlstrom",'id':75},
    {'bookTitle':"Yesterday",'imgUrl': 'foobar','author':"Graham Elsmore",'id':76},
    {'bookTitle':"Katt Williams: Priceless: Afterlife",'imgUrl': 'foobar','author':"Devonna Tibols",'id':77},
    {'bookTitle':"Aliens of the Deep",'imgUrl': 'foobar','author':"Elia Spears",'id':78},
    {'bookTitle':"Dead Bang",'imgUrl': 'foobar','author':"Shandee McSaul",'id':79},
    {'bookTitle':"Young Guns",'imgUrl': 'foobar','author':"Catina Lamkin",'id':80},
    {'bookTitle':"Firecracker",'imgUrl': 'foobar','author':"Nickey Bungey",'id':81},
    {'bookTitle':"Future, The",'imgUrl': 'foobar','author':"Noni Moggie",'id':82},
    {'bookTitle':"Nasty Girl, The (schreckliche Mädchen, Das)",'imgUrl': 'foobar','author':"Franky Minker",'id':83},
    {'bookTitle':"Battlefield Baseball (Jigoku kôshien)",'imgUrl': 'foobar','author':"Malcolm Bwy",'id':84},
    {'bookTitle':"Chronicle of Anna Magdalena Bach, The (Chronik der Anna Magdalena Bach)",'imgUrl': 'foobar','author':"Kassia Kirkland",'id':85},
    {'bookTitle':"Prince of the Sun: The Great Adventure of Horus (Taiyou no ouji Horusu no daibouken)",'imgUrl': 'foobar','author':"Nisse MacIlraith",'id':86},
    {'bookTitle':"Jesse Stone: Night Passage",'imgUrl': 'foobar','author':"Cristie Camili",'id':87},
    {'bookTitle':"El Escarabajo de Oro",'imgUrl': 'foobar','author':"Ivor Vasechkin",'id':88},
    {'bookTitle':"Flesh",'imgUrl': 'foobar','author':"Lucien Tupp",'id':89},
    {'bookTitle':"Hearts of Darkness: A Filmmakers Apocalypse",'imgUrl': 'foobar','author':"Kele Penman",'id':90},
    {'bookTitle':"Something Real and Good",'imgUrl': 'foobar','author':"Valeda Weerdenburg",'id':91},
    {'bookTitle':"Ishtar",'imgUrl': 'foobar','author':"Fabio Hewes",'id':92},
    {'bookTitle':"Grace Lee Project, The",'imgUrl': 'foobar','author':"Lindie Cofax",'id':93},
    {'bookTitle':"License to Wed",'imgUrl': 'foobar','author':"Abner Wurst",'id':94},
    {'bookTitle':"Sin City: A Dame to Kill For",'imgUrl': 'foobar','author':"Susanetta Danelutti",'id':95},
    {'bookTitle':"Thorn Birds, The",'imgUrl': 'foobar','author':"Jenna Grob",'id':96},
    {'bookTitle':"Pornographers, The (Erogotoshi-tachi yori: Jinruigaku nyûmon)",'imgUrl': 'foobar','author':"Liesa Peddel",'id':97},
    {'bookTitle':"Rumble Fish",'imgUrl': 'foobar','author':"Roxine Shellard",'id':98},
    {'bookTitle':"Star!",'imgUrl': 'foobar','author':"Werner Faier",'id':99},
    {'bookTitle':"Witches' Hammer (Kladivo na carodejnice) ",'imgUrl': 'foobar','author':"Devina Wyld",'id':100},
]
