services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/src/utils/logging/logs:/home/appuser/src/utils/logging/logs
    env_file: ".env"
