"""initial migration

Revision ID: 126928229fc9
Revises: 
Create Date: 2024-04-08 14:53:09.926818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126928229fc9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('create_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('referrer_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('create_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('userbooks',
    sa.Column('pk', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('book_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userbooks')
    op.drop_table('users')
    op.drop_table('books')
    # ### end Alembic commands ###
