export const users = [
    {
      "username": "Jeff Word Nerd",
      "created_date": "20230801",
      "book_ids": [1, 2, 3, 4],
      "review_ids": ["01", "02", "03"],
      "to_read_ids": [],
      "liked_authors": [],
      "liked_genres": [],
      "currently_reading": [],
      "friends": [],
      "is_friends_with_dummy": true,
      "liked_reviews": [],
      "email": "JeffLuvsBooks@gmail.com",
      "full_name": "Jeff Lowvowski",
      "disabled": false
    },
    {
      "username": "AnotherBookLover",
      "created_date": "20230802",
      "book_ids": [5, 6, 7],
      "review_ids": ["04", "05"],
      "to_read_ids": [8, 9],
      "liked_authors": ["AuthorA", "AuthorB"],
      "liked_genres": ["Mystery", "Science Fiction"],
      "currently_reading": [10],
      "friends": ["Jeff Word Nerd"],
      "is_friends_with_dummy": false,
      "liked_reviews": ["01"],
      "email": "AnotherLover@gmail.com",
      "full_name": "Alice Bookington",
      "disabled": false
    },
    {
        "username": "Bookworm123",
        "created_date": "20230803",
        "book_ids": [11, 12],
        "review_ids": ["06"],
        "to_read_ids": [13],
        "liked_authors": ["AuthorC"],
        "liked_genres": ["Fantasy"],
        "currently_reading": [11],
        "friends": ["AnotherBookLover"],
        "is_friends_with_dummy": true,
        "liked_reviews": ["02"],
        "email": "Bookworm123@example.com",
        "full_name": "Sarah Reader",
        "disabled": false
      },
      {
        "username": "LiteraryFanatic",
        "created_date": "20230804",
        "book_ids": [14, 15, 16],
        "review_ids": ["07", "08"],
        "to_read_ids": [17, 18],
        "liked_authors": ["AuthorD"],
        "liked_genres": ["Historical Fiction"],
        "currently_reading": [15],
        "friends": ["Bookworm123"],
        "is_friends_with_dummy": false,
        "liked_reviews": ["03"],
        "email": "FanaticLiterary@example.com",
        "full_name": "Emily Bookman",
        "disabled": false
      },
      {
        "username": "PageFlipper",
        "created_date": "20230819",
        "book_ids": [19, 20, 21],
        "review_ids": ["09", "10"],
        "to_read_ids": [22, 23],
        "liked_authors": ["AuthorE", "AuthorF"],
        "liked_genres": ["Thriller", "Mystery"],
        "currently_reading": [19],
        "friends": ["LiteraryFanatic"],
        "is_friends_with_dummy": true,
        "liked_reviews": ["04"],
        "email": "PageFlipper@email.com",
        "full_name": "Mark Turner",
        "disabled": false
      },
      {
        "username": "BookishJoy",
        "created_date": "20230825",
        "book_ids": [24],
        "review_ids": ["11"],
        "to_read_ids": [25],
        "liked_authors": ["AuthorG"],
        "liked_genres": ["Romance"],
        "currently_reading": [],
        "friends": ["PageFlipper"],
        "is_friends_with_dummy": false,
        "liked_reviews": ["05"],
        "email": "JoyfulReader@example.com",
        "full_name": "Joy Anderson",
        "disabled": false
      },
      {
        "username": "SciFiAficionado",
        "created_date": "20230903",
        "book_ids": [26, 27],
        "review_ids": ["12"],
        "to_read_ids": [28, 29],
        "liked_authors": ["AuthorH"],
        "liked_genres": ["Science Fiction"],
        "currently_reading": [26],
        "friends": ["BookishJoy"],
        "is_friends_with_dummy": true,
        "liked_reviews": ["06"],
        "email": "SciFiLover@example.com",
        "full_name": "Alex Reynolds",
        "disabled": false
      },
      {
        "username": "ClassicReader",
        "created_date": "20230910",
        "book_ids": [30, 31, 32],
        "review_ids": ["13", "14"],
        "to_read_ids": [33],
        "liked_authors": ["AuthorI"],
        "liked_genres": ["Classic Literature"],
        "currently_reading": [31],
        "friends": ["SciFiAficionado"],
        "is_friends_with_dummy": false,
        "liked_reviews": ["07"],
        "email": "ClassicReader@email.com",
        "full_name": "Eleanor Thompson",
        "disabled": false
      }
  ]
  