name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'bookmarks-frontend/**'

jobs:
  enable_eventbridge_rule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19.7.0'

    - name: Install dependencies
      run: |
        cd bookmarks-frontend
        npm install

    # - name: Run tests
    #   run: npm test

    - name: Build project
      run: npm run build

    - name: Deploy to S3
      run: aws s3 sync ./dist s3://book-prod-front-end-static-files --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'

    - name: Invalidate CloudFront
      run: aws cloudfront create-invalidation --distribution-id EWRREJ7Z0ZU5W --paths "/*"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'