name: Manage EventBridge Rule

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  enable_eventbridge_rule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.9'

    - name: Setup Docker Compose
      uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: '2.14.2' # the full version of `docker-compose` command

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Fetch secrets from AWS Secrets Manager
      run: |
        aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:788511695961:secret:dev/github-workflow-secrets-S6hWe8 --query SecretString --output text > backend/src/config/config.dev.json 

    - name: Start docker compose application
      run: |
        echo "GUNICORN_WORKERS=1" > .env
        echo "ENVIRONMENT=DEV" >> .env
        docker-compose up --build     
        sleep 60  # Give it a few seconds to start

    - name: Run tests
      env:
        PYTEST_SECRET: ${{ secrets.PYTEST_SECRET }}
      run: |
        cd backend/tests
        echo "{\"ADMIN_CREDENTIALS\": \"$PYTEST_SECRET\"}" > config.json
        pytest


    - name: Enable EventBridge Rule
      if: success()
      run: |
        aws events enable-rule --name TriggerStepFunctionAt5AM_EST